// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
*/


const sidebars = {

  Scripting: [{
    type: 'category',
    label: 'Scripting', 
    link: {type: 'doc', id: 'scripting/scripting'}, 
    items: [{type: 'autogenerated', dirName: 'scripting'}],
    collapsible: true,
    collapsed: true,
  }],
   MyServers: [{
    type: 'category',
    label: 'My Servers', 
    link: {type: 'doc', id: 'myservers/myservers'}, 
    items: [{type: 'autogenerated', dirName: 'myservers'}],
    collapsible: true,
    collapsed: true,
  }],
  implementations: [{
    type: 'category',
    label: 'Implementations', 
    link: {type: 'doc', id: 'implementations/implementations'}, 
    items: [{type: 'autogenerated', dirName: 'implementations'}],
    collapsible: true,
    collapsed: true,
  }],
  cooking: [{
    type: 'category',
    label: 'Cooking', 
    link: {type: 'doc', id: 'cooking/cooking'}, 
    items: [{type: 'autogenerated', dirName: 'cooking'}],
    collapsible: true,
    collapsed: true,
  }],
  general: [{
    type: 'category',
    label: 'General Documentation', 
    link: {type: 'doc', id: 'general/general'},
    items: [{type: 'autogenerated', dirName: 'general'}],
    collapsible: true,
    collapsed: true,
  }],
  
  intrests: [{type: 'autogenerated', dirName: 'intrests/intrests'}],
};


export default sidebars;
