// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
*/


const sidebars = {

  documentation: [{
    type: 'category',
    label: 'Documentation', 
    link: {type: 'doc', id: 'documentation/Documentation'}, 
    items: [{type: 'autogenerated', dirName: 'documentation'}],
    collapsible: true,
    collapsed: false,
  }],
  Intrests: [{type: 'autogenerated', dirName: 'Intrests'}],
};


export default sidebars;
